- hosts: frontend_service
  remote_user: root
  gather_facts: false
  vars:
    dest_root: /home/ubuntu
    nginx_serving_path: /var/www/html/petclinic
    nginx_config_path: /etc/nginx/nginx.conf
  tasks:
    - block:
        - name: Install node stack and proxy server
          package:
            name:
              - node
              - npm
              - nginx
            state: latest
            update_cache: true
        - name: Install angular
          npm:
            name: "@angular/cli@latest"
            global: yes
            state: latest
        - name: Create serving directory
          file:
            path: "{{nginx_serving_path}}"
            state: directory
            mode: "755"
        - name: Modify nginx config
          template:
            src: templates/frontend_nginx.j2
            dest: "{{nginx_config_path}}"
            mode: "644"
        - name: Start service
          systemd:
            name: nginx
            enabled: true
            state: started

      become: yes
      become_user: root
