- hosts: frontend_service
  strategy: free
  gather_facts: false
  vars:
    dest_root: /home/ubuntu
    nginx_serving_path: /var/www/html/petclinic
    nginx_config_path: /etc/nginx/sites-enabled/default
  tasks:
    - name: Install nginx server
      block:
        - name: Update cache
          apt:
            update_cache: true
        - name: Install nginx
          apt:
            name: nginx
            state: latest
      become: yes
      become_user: root
    - name: Configure server
      block:
        - name: Create serving directory
          file:
            path: "{{nginx_serving_path}}"
            state: directory
            mode: "755"
        - name: Modify nginx config
          template:
            src: templates/frontend_nginx.j2
            dest: "{{nginx_config_path}}"
            mode: "644"
        - name: Restart server
          systemd:
            name: nginx
            enabled: true
            state: restarted
      become: yes
      become_user: root
