- hosts: backend_service
  remote_user: root
  gather_facts: false
  vars:
    dest_root: /home/ubuntu
  tasks:
    - name: Install stack
      package:
        name:
          - default-jdk
          - maven
        state: latest
        update_cache: true
      become: yes
      become_user: root
