- hosts: backend_service
  tasks:
    - block:
        - name: Update cache
          apt:
            update_cache: true
        - name: Install java environment
          apt:
            name: openjdk-11-jdk
            state: latest
      become: yes
      become_user: root
