- hosts: backend_service
  tasks:
    - name: Install stack
      package:
        name:
          - default-jdk
          - maven
        state: latest
        update_cache: true
      become: yes
      become_user: root
