- hosts: backend_service
  strategy: free
  tasks:
    - name: Install java environment
      block:
        - name: Update cache
          apt:
            update_cache: true
        - name: Install java environment
          apt:
            name: openjdk-11-jdk
            state: latest
      become: yes
      become_user: root
