- hosts: database
  gather_facts: false
  tasks:
    - block:
        - name: Update cache
          apt:
            update_cache: true
        - name: Install postgres and dependancies
          apt:
            name:
              - postgresql
              - postgresql-contrib
              - libpq-dev
              - python3-psycopg2
              - acl
            state: latest
        - name: Make postgres available to public
          shell: |
            echo "listen_addresses = '*'" >> /etc/postgresql/12/main/postgresql.conf
            echo "host  all  all 0.0.0.0/0 md5" >> /etc/postgresql/12/main/pg_hba.conf
        - name: Restart postgres
          systemd:
            name: postgresql
            state: restarted
        - name: Create postgres database
          postgresql_db:
            name: "{{database}}"
        - name: Setup user and database
          postgresql_user:
            db: "{{database}}"
            name: "{{user_name}}"
            password: "{{user_password}}"
      become: true
      become_user: postgres
