- hosts: server
  remote_user: root
  gather_facts: false
  vars:
    dest_root: /home/ubuntu
  tasks:
    - block:
      - name: Install stack
        package:
          name:
            - default-jdk
            - maven
          state: latest
          update_cache: true

      - name: Clone rest server
        git:
          repo: https://github.com/spring-petclinic/spring-petclinic-rest.git
          dest: "{{dest_root}}/spring-petclinic-rest"

      - name: Build rest service
        shell: |
          cd "{{dest_root}}"/spring-petclinic-rest
          mvn clean package -DskipTests

      - name: Create service file
        template:
          src: rest.service.j2
          dest: /etc/systemd/system/petclinic-rest.service
          mode: 0644

      - name: Start service
        systemd:
          name: petclinic-rest
          state: started
          enabled: yes

      become: yes
      become_user: root
